allow promisc on joyent brand zones, add bridge and simnets.

diff --git a/overlay/generic/lib/svc/method/net-physical b/overlay/generic/lib/svc/method/net-physical
--- a/overlay/generic/lib/svc/method/net-physical
+++ b/overlay/generic/lib/svc/method/net-physical
@@ -81,6 +81,13 @@ function get_link_state
 {
     set -o xtrace
     link_state=$(/usr/sbin/dladm show-phys -po state $1 2>/dev/null)
+    if [[ -z $link_state ]] ; then
+      is_simnet=$(/usr/sbin/dladm show-simnet -p -o link $1 2>/dev/null)
+      if [[ -n $is_simnet ]]; then
+        # simnets are always up.
+        link_state="up"
+      fi
+    fi
 }
 
 # Waits for up to 10 seconds for the link state to change to the given value
@@ -423,19 +430,19 @@ function setup_mtu
             exit $SMF_EXIT_ERR_FATAL
         fi
 
-        #
-        # Check the current MTU of the device. To help out devices which
-        # don't support the setting of the MTU (here's looking at you
-        # bnx), if the MTU is identical to its default, don't do
-        # anything and save the poor folks stuck with bnx some grief.
-        #
-        curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
-        [[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
+	#
+	# Check the current MTU of the device. To help out devices which
+	# don't support the setting of the MTU (here's looking at you
+	# bnx), if the MTU is identical to its default, don't do
+	# anything and save the poor folks stuck with bnx some grief.
+	#
+	curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
+	[[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
 
-            if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
-                echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
-                exit $SMF_EXIT_ERR_FATAL
-            fi
+        if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
+            echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
+            exit $SMF_EXIT_ERR_FATAL
+        fi
     done
 }
 
@@ -491,6 +498,95 @@ if smf_is_globalzone; then
     for stub in $(echo "${CONFIG_etherstub}" | sed -e "s/,/ /g"); do
         /usr/sbin/dladm create-etherstub -t $stub || echo "ERROR: could not create etherstub ${stub}."
     done
+	
+    # Set up bridges
+    for bridge in $(echo "${CONFIG_bridge}" | sed -e "s/,/ /g"); do
+        /usr/sbin/dladm create-bridge $bridge || echo "ERROR: could not create bridge ${bridge}."
+    done
+
+    # Set up simnets
+    for simnet in $(echo "${CONFIG_simnet}" | sed -e "s/,/ /g"); do
+        /usr/sbin/dladm create-simnet $simnet || echo "ERROR: could not create simnet ${simnet}."
+    done
+	
+	# Connect simnets
+	for simnet in $(echo "${CONFIG_simnet}" | sed -e "s/,/ /g"); do
+        eval "snp=\${CONFIG_simnet_${simnet}_port}"
+        [[ -z "$snp" ]] && continue
+	/usr/sbin/dladm modify-simnet -p $snp $simnet || echo "ERROR: could not connect ${simnet} to port ${snp}."
+	done	
+	
+	# Add ports to bridges
+	for bridge in $(echo "${CONFIG_bridge}" | sed -e "s/,/ /g"); do
+        eval "brp=\${CONFIG_bridge_${bridge}_ports}"
+        [[ -z "$brp" ]] && continue
+		
+		for port in $(echo "$brp" | sed -e "s/,/ /g"); do
+		    eval "nic=\${SYSINFO_NIC_${port}}"
+		    echo NIC: $nic
+		
+		    [[ -n $nic ]] && port=$nic
+
+			echo PORT: $port
+			/usr/sbin/dladm add-bridge -l $port $bridge || echo "ERROR: could not add ${port} to bridge ${bridge}."
+		done
+	done
+    
+    # creating bridges and simnets may affect sysinfo, so refresh.
+    /usr/bin/sysinfo -u
+    load_sdc_sysinfo
+
+    # Set up bridges
+    for bridge in $(echo "${CONFIG_bridge}" | sed -e "s/,/ /g"); do
+        # if the bridge exists and has links, we must delete them before recreating (there is no temporay bridge option)
+	links=$(/usr/sbin/dladm show-bridge -ls -p -o link ${bridge} 2>/dev/null) \
+		&& echo "INFO: bridge ${bridge} exists, we will rebuild."
+	if [ $? -eq 0 ] ; then
+	  for link in $links ; do
+	    /usr/sbin/dladm remove-bridge -l $link $bridge
+	  done
+          /usr/sbin/dladm delete-bridge $bridge
+        fi
+        /usr/sbin/dladm create-bridge $bridge || echo "ERROR: could not create bridge ${bridge}."
+    done
+
+    # remove any old simnets
+    for old_simnet in $(/usr/sbin/dladm show-simnet -p -o link) ; do
+        /usr/sbin/dladm modify-simnet -p none ${old_simnet} || "WARN: could not remove connection from simnet ${old_simnet}."
+        /usr/sbin/dladm delete-simnet ${old_simnet} || echo "ERROR: could not delete old simnet ${old_simnet}."
+    done
+
+    # Set up simnets
+    for simnet in $(echo "${CONFIG_simnet}" | sed -e "s/,/ /g"); do
+        /usr/sbin/dladm create-simnet $simnet || echo "ERROR: could not create simnet ${simnet}."
+    done
+
+	# Connect simnets
+	for simnet in $(echo "${CONFIG_simnet}" | sed -e "s/,/ /g"); do
+        eval "snp=\${CONFIG_simnet_${simnet}_port}"
+        [[ -z "$snp" ]] && continue
+	/usr/sbin/dladm modify-simnet -p $snp $simnet || echo "ERROR: could not connect ${simnet} to port ${snp}."
+	done	
+	
+	# Add ports to bridges
+	for bridge in $(echo "${CONFIG_bridge}" | sed -e "s/,/ /g"); do
+        eval "brp=\${CONFIG_bridge_${bridge}_ports}"
+        [[ -z "$brp" ]] && continue
+		
+		for port in $(echo "$brp" | sed -e "s/,/ /g"); do
+		    eval "nic=\${SYSINFO_NIC_${port}}"
+		    echo NIC: $nic
+		
+		    [[ -n $nic ]] && port=$nic
+
+			echo PORT: $port
+			/usr/sbin/dladm add-bridge -l $port $bridge || echo "ERROR: could not add ${port} to bridge ${bridge}."
+		done
+	done
+    
+    # creating bridges and simnets may affect sysinfo, so refresh.
+    /usr/bin/sysinfo -u
+    load_sdc_sysinfo
 
     # Create aggregations
     create_aggrs
@@ -526,19 +622,19 @@ if smf_is_globalzone; then
         fi
 
         nictagadm list
-    elif [[ -v CONFIG_admin_tag ]]; then
-        #
-        # This handles the case when the 'admin_tag' property is set to
-        # override the default admin nic tag.
-        #
-        eval SYSINFO_NIC_admin='$'SYSINFO_NIC_${CONFIG_admin_tag}
-
-        eval CONFIG_admin_ip='$'CONFIG_${CONFIG_admin_tag}_ip
-        eval CONFIG_admin_ip6='$'CONFIG_${CONFIG_admin_tag}_ip6
-        eval CONFIG_admin_netmask='$'CONFIG_${CONFIG_admin_tag}_netmask
-        eval CONFIG_admin_mtu='$'CONFIG_${CONFIG_admin_tag}_mtu
-        eval CONFIG_admin_gateway='$'CONFIG_${CONFIG_admin_tag}_gateway
-        eval CONFIG_admin_gateway6='$'CONFIG_${CONFIG_admin_tag}_gateway6
+      elif [[ -v CONFIG_admin_tag ]]; then
+	        #
+	        # This handles the case when the 'admin_tag' property is set to
+	        # override the default admin nic tag.
+	        #
+	        eval SYSINFO_NIC_admin='$'SYSINFO_NIC_${CONFIG_admin_tag}
+	
+	        eval CONFIG_admin_ip='$'CONFIG_${CONFIG_admin_tag}_ip
+	        eval CONFIG_admin_ip6='$'CONFIG_${CONFIG_admin_tag}_ip6
+	        eval CONFIG_admin_netmask='$'CONFIG_${CONFIG_admin_tag}_netmask
+	        eval CONFIG_admin_mtu='$'CONFIG_${CONFIG_admin_tag}_mtu
+	        eval CONFIG_admin_gateway='$'CONFIG_${CONFIG_admin_tag}_gateway
+	        eval CONFIG_admin_gateway6='$'CONFIG_${CONFIG_admin_tag}_gateway6
     fi
 
     if [[ -z "${SYSINFO_NIC_admin}" ]]; then
